### ISSUE TITLE
Buttons , animation and speed related 

### ISSUE THREAD

**Issue by kingap7** [Bhavya0304/ProductSysOnAttributeChange#1]
So i analyze your code and find some issues which i am sharing to you.. 
first is when i hover on main picture and change color of shirt and hover again then it's shows old image as result in hover .. so that thing need to be fixed
second is that buttons are not working... maybe you don't want to make any complex thing. so you can just pass to massage about product added to cart. also you use so big files in javascript for your animations. as per i think  it makes your app very slow . so you should just remove unnecessary code form project..

Thank You  👍

**Comment by Bhavya0304** [comment]
loda aae office mate prototype model che khali angular thi
attribute selection nu..

**Comment by Bhavya0304** [comment]
Please Note that this Isn't any public project but work related , due to some work rules I am unable to make it private so this is just a prototype model and not a project to raise issue on...
